# Generated by Django 5.0.6 on 2024-05-30 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('tipo', models.CharField(choices=[('futbol_5', 'Fútbol 5'), ('futbol_7', 'Fútbol 7'), ('futbol_11', 'Fútbol 11')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_persona', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('es_empleado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alquiler', models.DateField()),
                ('turno', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10)),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_alquiler.cancha')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_alquiler.salon')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alquiler.usuario')),
            ],
        ),
    ]
