# Generated by Django 5.0.6 on 2024-06-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_alquiler', '0002_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquiler',
            options={'verbose_name': 'Alquiler', 'verbose_name_plural': 'Alquileres'},
        ),
        migrations.AlterModelOptions(
            name='cancha',
            options={'verbose_name': 'Cancha', 'verbose_name_plural': 'Canchas'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'Salon', 'verbose_name_plural': 'Salones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='alquiler',
            table='Alquileres',
        ),
        migrations.AlterModelTable(
            name='cancha',
            table='Canchas',
        ),
        migrations.AlterModelTable(
            name='contacto',
            table='Contactos',
        ),
        migrations.AlterModelTable(
            name='salon',
            table='Salones',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuarios',
        ),
    ]
