# Generated by Django 5.0.6 on 2024-06-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alquiler', '0004_alter_usuario_options_usuario_last_login_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='es_empleado',
            field=models.BooleanField(),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuarios',
        ),
    ]
