# Generated by Django 5.0.6 on 2024-06-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alquiler', '0005_alter_usuario_options_remove_usuario_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
