# Generated by Django 5.0.6 on 2024-06-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alquiler', '0007_alter_usuario_managers_remove_usuario_es_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, default='Sin numero registrado', max_length=25),
        ),
    ]
