# Generated by Django 5.0.6 on 2024-06-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_alquiler', '0010_perfilusuario'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
    ]
