# Generated by Django 5.0.6 on 2024-06-11 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alquiler', '0013_rename_user_usuario_alter_perfilusuario_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'Salón', 'verbose_name_plural': 'Salones'},
        ),
        migrations.AddField(
            model_name='alquiler',
            name='cantidad_personas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='horas_alquiler',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='invitados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salon',
            name='precio_persona',
            field=models.IntegerField(default=750),
        ),
    ]
