# Generated by Django 5.0.6 on 2024-06-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alquiler', '0014_alter_salon_options_alquiler_cantidad_personas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='cantidad_personas',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='horas_alquiler',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
