# Generated by Django 5.0.6 on 2024-06-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alquiler', '0015_alter_alquiler_cantidad_personas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='precio_hora',
            field=models.IntegerField(default=1800),
        ),
    ]
