# Generated by Django 5.0.6 on 2024-06-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_alquiler', '0016_cancha_precio_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
